### ISSUE TITLE
react fails to build with 4.14.0+trunk

### ISSUE THREAD

**Issue by shubhamkumar13** [dbuenzli/react#34]
I get the following error log when I try to build `react` with `4.14.0+trunk` and `dune.2.9.0`

```
#=== ERROR while compiling react.1.2.1 ========================================#
# context     2.0.8 | linux/x86_64 | ocaml-variants.4.14.0+trunk | https://opam.ocaml.org#1fc79772
# path        ~/.opam/4.14.0+trunk/.opam-switch/build/react.1.2.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build ocaml pkg/pkg.ml build --dev-pkg false
# exit-code   1
# env-file    ~/.opam/log/react-2325867-d2c37b.env
# output-file ~/.opam/log/react-2325867-d2c37b.out
### output ###
# [...]
# findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /home/sk/.opam/4.14.0+trunk/lib/ocaml, /home/sk/.opam/4.14.0+trunk/lib/ocaml/compiler-libs
# File "src/react_top.ml", line 7, characters 17-33:
# 7 | let () = ignore (Toploop.use_file Format.err_formatter "react_top_init.ml")
#                      ^^^^^^^^^^^^^^^^
# Error: Unbound value Toploop.use_file
# Command exited with code 2.
# pkg.ml: [ERROR] cmd ['ocamlbuild' '-use-ocamlfind' '-classic-display' '-j' '4' '-tag' 'debug'
#      '-build-dir' '_build' 'opam' 'pkg/META' 'CHANGES.md' 'LICENSE.md'
#      'README.md' 'src/react.a' 'src/react.cmxs' 'src/react.cmxa'
#      'src/react.cma' 'src/react.cmx' 'src/react.cmi' 'src/react.mli'
#      'src/react_top.a' 'src/react_top.cmxs' 'src/react_top.cmxa'
#      'src/react_top.cma' 'src/react_top.cmx' 'src/react_top_init.ml']: exited with 10

```

**Comment by dbuenzli** [comment]
See https://github.com/ocaml/ocaml/issues/10556
